version: "3.8"

services:
  apache:
    image: httpd:2.4
    ports:
      - "1234:80"
    volumes:
      - ./server:/usr/local/apache2/htdocs
  client:
    build: client/
    network_mode: host
    command: python ./client.py
    depends_on:
      - apache
